### ISSUE TITLE
Error with IE9 - invalid Argument

### ISSUE THREAD

**Issue by rogergl** [davidsantiago/hickory#21]
The argument "text/html" is wrong for IE9.

(defn parse-dom-with-domparser ...
   (.parseFromString (js/DOMParser.) s "text/html")))

See the following link for supported arguments:
http://msdn.microsoft.com/en-us/library/ie/ff975278(v=vs.85).aspx

**Comment by jeluard** [comment]
Have you experimented with those? Looks like none could parse generic HTML.
Are you aware of an alternative?

**Comment by robert-stuttaford** [comment]
@jeluard we've just bumped our head against this as well. I can confirm that IE9 doesn't accept `"text/html"` as an argument. I see that your code has a fallback - can you not somehow force that fallback method on IE9?

**Comment by jeluard** [comment]
That could be an option indeed. Could you confirm the fallback works fine on IE9?
Also do you know of a reasonable way to detect this scenario?

Please feel free to send a PR! :)

**Comment by robert-stuttaford** [comment]
The polyfill works perfectly. I suggest including a section in your readme about it. I didn't dig into detection once the polyfill proved to work! -expletive deleted- IE9 -grumble-.
