### ISSUE TITLE
Unary tag parsing

### ISSUE THREAD

**Issue by tobynance** [davidsantiago/hickory#31]
A unary `span` tag is being interpreted as extending to the end of the surrounding `p`.
```clojure
(defn round-trip [text]
  (->
    text
    hickory.core/parse-fragment
    first
    hickory.core/as-hickory
    hickory.render/hickory-to-html))
(round-trip "<p>this<span/> is a test.</p>")
"<p>this<span> is a test.</span></p>"
```
It will also extend outside of a surrounding `span` element.
```clojure
(round-trip "<p><span>this<span /> is a </span>test.</p>")
"<p><span>this<span> is a </span>test.</span></p>"
```
Is there a way to avoid this behavior? I need to clean up html which may include empty elements.

**Comment by davidsantiago** [comment]
Hm, I'm not sure what to do about this. From what I can find, the self-closing tag doesn't have the same interpretation in HTML5: http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5 In any case, we don't do any HTML parsing in Hickory, we rely on JSoup. If you have HTML that is in XHTML form, as that appears to be, you may need to user an XHTML to HTML5 converter before it goes into Hickory.

**Comment by tobynance** [comment]
Gotcha.  Thank you for the update.  I don't always know whether the incoming content will be HTML5 or XHTML, but I will work on recognizing which it is before calling into Hickory.  Thank you.
