### ISSUE TITLE
Case sensitive tags/attributes

### ISSUE THREAD

**Issue by kovacnica** [davidsantiago/hickory#37]
Hi,

I'm working on project where we are using hickory as part of our client interface towards REST backend application. Backend is providing XML that contains case sensitive tags that refer to JAVA classes.

Hickory has hardcoded cast of attribute names and tags to lower-case-keyword. Is it possible to make it more transparent and leave that job to end user. To use zipper/walk to change keys?

Tnx,
Robert

**Comment by davidsantiago** [comment]
I'm not sure. Hickory assumes HTML throughout the pipeline, and I really
don't know that much about XML, so I haven't thought about the extent to
which you can send XML through there. Do you have a specific change in
mind, or are you asking if I know how to make it happen? Answer to the
second one is no, I'm afraid.

**Comment by kovacnica** [comment]
Hi,

Tnx for quick feedback. I've found out that similar issue has already been opened.
https://github.com/davidsantiago/hickory/pull/22

So I guess that olivergeorge is already working on it. Tnx, as far as I'm concerned issue is closed...
