### ISSUE TITLE
CSS Support

### ISSUE THREAD

**Issue by flyboarder** [davidsantiago/hickory#39]
Is hickory open to PR's for css support?

**Comment by davidsantiago** [comment]
What does that entail? Do you mean css selectors that are missing from the current set of selectors? When I wrote this originally, I implemented what I thought was a spanning set of selectors that could do most of what the CSS selectors did on a static page. Most of the others require dynamic page state or are somewhat redundant. But, I haven't looked in a while, I know new ones are added all the time.

**Comment by flyboarder** [comment]
I am referring to reading and writing css files.
See gist: https://gist.github.com/flyboarder/d14e825737d50a6f141717f9c263e239

**Comment by davidsantiago** [comment]
This does look really interesting! What do you use it for? Is there a synergy to using it with Hickory's HTML support?

**Comment by flyboarder** [comment]
@davidsantiago there is great synergy, currently using it for a boot-clj task, inlining css into html files. The task reads the `link` hickory tag, looks up the file and parses it into a css version of the hickory structure, then I convert that structure into a hickory `style` tag, and replace the original `link`.
I have created a new repo for the project here: https://github.com/degree9/dickory-dock may ad js support in the future.

Also, this repo doesnt duplicate any hickory code, so hickory is needed for things like the select namespace.

**Comment by davidsantiago** [comment]
Right, the reason I was asking was because you've clearly done a lot of work here to get it going, and it seems like a thing that could be useful on its own. So I was wondering why you want it in Hickory. I'd take it, of course, but I wonder if you wouldn't rather have it be your project, unless there is some reason it makes sense to merge them together. Happy to do what you prefer here.

**Comment by flyboarder** [comment]
When I initially opened this issue I had only a bit of the project working, it is larger now and could probably be left as it's own project. If there is a large demand for using both of them we can always merge it later.

**Comment by davidsantiago** [comment]
Sounds good.
