### ISSUE TITLE
Unexpected conversion result

### ISSUE THREAD

**Issue by ezmiller** [davidsantiago/hickory#49]
I did the following:
```
(map as-hiccup (parse-fragment "<p><div>test</div></p>"))
```
And got:
```
([:p {}] [:div {} "test"] [:p {}])
```
Note that the `p` tags are independent empty tags, but this isn't a correct conversion I don't think. Am I missing something? Or is this a bug?

Incidentally, if I do:
```
(map as-hiccup (parse-fragment "<div><div>test</div></div>"))
```
The result seem as it should be:
```
([:div {} [:div {} "test"]])
```

**Comment by davidsantiago** [comment]
I'm honestly not sure... I know that P is one of the HTML tags that is a "void" tag and shouldn't have a closing tag, although I have seen closing tags before. When I run your example through an HTML5 validator, it doesn't like the </p> tag, and Hickory does use an HTML5 parser. So I'm not sure what to tell you, perhaps someone who is more familiar with the intricacies of HTML5 can weigh in.

**Comment by davidsantiago** [comment]
According to this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p, 

`The start tag is required. The end tag may be omitted if the <p> element is immediately followed by an <address>, <article>, <aside>, <blockquote>, <div>, <dl>, <fieldset>, <footer>, <form>, <h1>, <h2>, <h3>, <h4>, <h5>, <h6>, <header>, <hr>, <menu>, <nav>, <ol>, <pre>, <section>, <table>, <ul> or another <p> element, or if there is no more content in the parent element and the parent element is not an <a> element.`

So the way I read that is that the div following the p element implicitly closes the p element, and then it doesn't like seeing the closing p tag.

**Comment by ezmiller** [comment]
Very interesting. I guess that's the answer then. Thanks for the response.
