### ISSUE TITLE
:viewBox property in svg not correctly parsed to hiccup.

### ISSUE THREAD

**Issue by MawiraIke** [davidsantiago/hickory#59]
Totally enjoying the simplicity of using this library. I am trying to convert a SVG html string to hiccup but I noticed that the ```:viewBox``` property in svg's is not correctly parsed. The output is ```:viewbox``` instead of ```:viewBox``` which is not correctly translated by the browser hence the resulting svg is not displayed correctly.  I am using the ```parse-fragment``` function although I noticed the issue also occurs in ```parse```. The rest of the string is parsed correctly as far as I can tell. This is not a big issue since clojure has ```clojure.walk/postwalk``` which can easily fix this on the resulting hiccup but I guess it would be better to be implemented in the library. If this issue is not worked on soon, can I look into it later when I get time and make a PR?

**Comment by cassc** [comment]
In html, attribute names are case-insensitive, Jsoup, which this library depends on, also [converts attribute names to lower case intentionally](https://github.com/jhy/jsoup/issues/981).

**Comment by MawiraIke** [comment]
Thanks for the reply. That must be wierd since the case sensitivity wasn't working for me. The svg was plotted but the viewBox was not obeyed. I will check my code.

Since this issue seems like its already known, I will close this Issue. Thanks again for the reply.
